---
abstract: 'a software model for a set of collated texts'
author:
  - 'Tara L Andrews <aurum@cpan.org>'
build_requires:
  Data::Dump: 0
  ExtUtils::MakeMaker: 6.59
  Test::More::UTF8: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Text::Tradition
name: Text-Tradition
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::Diff: 0
  File::Which: 0
  Graph: 0
  IPC::Run: 0
  JSON: 0
  Module::Load: 0
  Moose: 0
  Moose::Util: 0
  Moose::Util::TypeConstraints: 0
  Safe::Isa: 0
  Spreadsheet::ParseExcel: 0
  Spreadsheet::XLSX: 0
  StackTrace::Auto: 0
  Text::CSV: 0
  Text::TEI::Markup: 1.7
  Throwable::X: 0
  TryCatch: 0
  XML::Easy::Syntax: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  perl: 5.12.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.3
